export const QUALITY_OPTIONS = [
  { label: 'All', value: 'all' },
  { label: '720p', value: '720p' },
  { label: '1080p', value: '1080p' },
  { label: '2160p', value: '2160p' },
  { label: '3D', value: '3d' },
];

export const GENRE_OPTIONS = [
  { label: 'All', value: 'all' },
  { label: 'Action', value: 'action' },
  { label: 'Adventure', value: 'adventure' },
  { label: 'Animation', value: 'animation' },
  { label: 'Biography', value: 'biography' },
  { label: 'Comedy', value: 'comedy' },
  { label: 'Crime', value: 'crime' },
  { label: 'Documentary', value: 'documentary' },
  { label: 'Drama', value: 'drama' },
  { label: 'Family', value: 'family' },
  { label: 'Fantasy', value: 'fantasy' },
  { label: 'Film-Noir', value: 'film-noir' },
  { label: 'Game-Show', value: 'game-show' },
  { label: 'History', value: 'history' },
  { label: 'Horror', value: 'horror' },
  { label: 'Music', value: 'music' },
  { label: 'Musical', value: 'musical' },
  { label: 'Mystery', value: 'mystery' },
  { label: 'News', value: 'news' },
  { label: 'Reality-TV', value: 'reality-tv' },
  { label: 'Romance', value: 'romance' },
  { label: 'Sci-Fi', value: 'sci-fi' },
  { label: 'Short', value: 'short' },
  { label: 'Sport', value: 'sport' },
  { label: 'Talk-Show', value: 'talk-show' },
  { label: 'Thriller', value: 'thriller' },
  { label: 'War', value: 'war' },
  { label: 'Western', value: 'western' },
];

export const SORT_BY_OPTIONS = [
  { label: 'Date Added', value: 'date_added' },
  { label: 'Title', value: 'title' },
  { label: 'Year', value: 'year' },
  { label: 'Rating', value: 'rating' },
  { label: 'Peers', value: 'peers' },
  { label: 'Seeds', value: 'seeds' },
  { label: 'Download Count', value: 'download_count' },
  { label: 'Like Count', value: 'like_count' },
];
